### ISSUE TITLE
Guzzle Update

### ISSUE THREAD

**Issue by jurgenhaas** [platformsh/platformsh-client-php#19]
This has been asked before in #9 but I have to raise the issue again, at least this is now 2 years down the road.

My issue comes from a Drupal 8.4 context where I have to live inside of a composer based workflow. And as I want to integrate PlatformSH with my DRD module, I do need your library as a composer package and not a phar, simply to have the components available from autoloader.

I thought I'd ask that question again, because eventually you would have to switch to something higher than 5.x for Guzzle anyway, you wouldn't want to sit on that for ever, do you?

**Comment by pjcdawkins** [comment]
Agreed, it needs an update, maybe to Guzzle 6, maybe to something different (personally I'm tempted by https://github.com/reactphp/http-client).

**Comment by jurgenhaas** [comment]
Well, I'd be happy with Guzzle 6, simply because it is already present in the Drupal environment and we don't need 2 different http clients, I guess.

**Comment by pjcdawkins** [comment]
You can now use version `^2.0@beta` (or `dev-master`) with Guzzle 6.

**Comment by jurgenhaas** [comment]
Thanks, works great.
