### ISSUE TITLE
Error when trying to invite a user

### ISSUE THREAD

**Issue by fabpot** [platformsh/platformsh-client-php#64]
When trying to add a user, I get the following exception:

ArgumentCountError: Too few arguments to function Platformsh\Client\Model\Invitation\AlreadyInvitedException::__construct(), 5 passed in phar:///home/fabien/.platformsh/bin/platform/vendor/platformsh/client/src/Model/Project.php on line 177 and exactly 6 expected in phar:///home/fabien/.platformsh/bin/platform/vendor/platformsh/client/src/Model/Invitation/AlreadyInvitedException.php on line 25

If you have a look at the code, there is indeed 6 args on the AlreadyInvitedException exception, but only 5 are passed to the contructor.

**Comment by pjcdawkins** [comment]
Thank you - fixed in 0.55.4
